/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVehiclesRouteImport } from './routes/_app/vehicles'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRemindersRouteImport } from './routes/_app/reminders'
import { Route as AppPromotionsRouteImport } from './routes/_app/promotions'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppMaintenanceRouteImport } from './routes/_app/maintenance'
import { Route as AppInspectionsRouteImport } from './routes/_app/inspections'
import { Route as AppFormDesignRouteImport } from './routes/_app/form-design'
import { Route as AppDriversRouteImport } from './routes/_app/drivers'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppBookingsIndexRouteImport } from './routes/_app/bookings.index'
import { Route as AppBookingsNewRouteImport } from './routes/_app/bookings/new'
import { Route as AppAiWhatsappRouteImport } from './routes/_app/ai/whatsapp'
import { Route as AppAiVoiceBookingRouteImport } from './routes/_app/ai/voice-booking'
import { Route as AppAiTranslateRouteImport } from './routes/_app/ai/translate'
import { Route as AppAiSummarizeRouteImport } from './routes/_app/ai/summarize'
import { Route as AppAiSmartSearchRouteImport } from './routes/_app/ai/smart-search'
import { Route as AppAiSignatureVerifyRouteImport } from './routes/_app/ai/signature-verify'
import { Route as AppAiRiskRouteImport } from './routes/_app/ai/risk'
import { Route as AppAiRecommendRouteImport } from './routes/_app/ai/recommend'
import { Route as AppAiPricingRouteImport } from './routes/_app/ai/pricing'
import { Route as AppAiOcrCnicRouteImport } from './routes/_app/ai/ocr-cnic'
import { Route as AppAiMaintenanceRouteImport } from './routes/_app/ai/maintenance'
import { Route as AppAiFraudRouteImport } from './routes/_app/ai/fraud'
import { Route as AppAiForecastRouteImport } from './routes/_app/ai/forecast'
import { Route as AppAiDamageRouteImport } from './routes/_app/ai/damage'
import { Route as AppAiChatRouteImport } from './routes/_app/ai/chat'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotionsRoute = AppPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppFormDesignRoute = AppFormDesignRouteImport.update({
  id: '/form-design',
  path: '/form-design',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIndexRoute = AppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsNewRoute = AppBookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAiWhatsappRoute = AppAiWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiVoiceBookingRoute = AppAiVoiceBookingRouteImport.update({
  id: '/voice-booking',
  path: '/voice-booking',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiTranslateRoute = AppAiTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiSummarizeRoute = AppAiSummarizeRouteImport.update({
  id: '/summarize',
  path: '/summarize',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiSmartSearchRoute = AppAiSmartSearchRouteImport.update({
  id: '/smart-search',
  path: '/smart-search',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiSignatureVerifyRoute = AppAiSignatureVerifyRouteImport.update({
  id: '/signature-verify',
  path: '/signature-verify',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiRiskRoute = AppAiRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiRecommendRoute = AppAiRecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiPricingRoute = AppAiPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiOcrCnicRoute = AppAiOcrCnicRouteImport.update({
  id: '/ocr-cnic',
  path: '/ocr-cnic',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiMaintenanceRoute = AppAiMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiFraudRoute = AppAiFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiForecastRoute = AppAiForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiDamageRoute = AppAiDamageRouteImport.update({
  id: '/damage',
  path: '/damage',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiChatRoute = AppAiChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppAiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai': typeof AppAiRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/drivers': typeof AppDriversRoute
  '/form-design': typeof AppFormDesignRoute
  '/inspections': typeof AppInspectionsRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/payments': typeof AppPaymentsRoute
  '/promotions': typeof AppPromotionsRoute
  '/reminders': typeof AppRemindersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/vehicles': typeof AppVehiclesRoute
  '/ai/chat': typeof AppAiChatRoute
  '/ai/damage': typeof AppAiDamageRoute
  '/ai/forecast': typeof AppAiForecastRoute
  '/ai/fraud': typeof AppAiFraudRoute
  '/ai/maintenance': typeof AppAiMaintenanceRoute
  '/ai/ocr-cnic': typeof AppAiOcrCnicRoute
  '/ai/pricing': typeof AppAiPricingRoute
  '/ai/recommend': typeof AppAiRecommendRoute
  '/ai/risk': typeof AppAiRiskRoute
  '/ai/signature-verify': typeof AppAiSignatureVerifyRoute
  '/ai/smart-search': typeof AppAiSmartSearchRoute
  '/ai/summarize': typeof AppAiSummarizeRoute
  '/ai/translate': typeof AppAiTranslateRoute
  '/ai/voice-booking': typeof AppAiVoiceBookingRoute
  '/ai/whatsapp': typeof AppAiWhatsappRoute
  '/bookings/new': typeof AppBookingsNewRoute
  '/bookings/': typeof AppBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai': typeof AppAiRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/drivers': typeof AppDriversRoute
  '/form-design': typeof AppFormDesignRoute
  '/inspections': typeof AppInspectionsRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/payments': typeof AppPaymentsRoute
  '/promotions': typeof AppPromotionsRoute
  '/reminders': typeof AppRemindersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/vehicles': typeof AppVehiclesRoute
  '/ai/chat': typeof AppAiChatRoute
  '/ai/damage': typeof AppAiDamageRoute
  '/ai/forecast': typeof AppAiForecastRoute
  '/ai/fraud': typeof AppAiFraudRoute
  '/ai/maintenance': typeof AppAiMaintenanceRoute
  '/ai/ocr-cnic': typeof AppAiOcrCnicRoute
  '/ai/pricing': typeof AppAiPricingRoute
  '/ai/recommend': typeof AppAiRecommendRoute
  '/ai/risk': typeof AppAiRiskRoute
  '/ai/signature-verify': typeof AppAiSignatureVerifyRoute
  '/ai/smart-search': typeof AppAiSmartSearchRoute
  '/ai/summarize': typeof AppAiSummarizeRoute
  '/ai/translate': typeof AppAiTranslateRoute
  '/ai/voice-booking': typeof AppAiVoiceBookingRoute
  '/ai/whatsapp': typeof AppAiWhatsappRoute
  '/bookings/new': typeof AppBookingsNewRoute
  '/bookings': typeof AppBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/ai': typeof AppAiRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/drivers': typeof AppDriversRoute
  '/_app/form-design': typeof AppFormDesignRoute
  '/_app/inspections': typeof AppInspectionsRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/promotions': typeof AppPromotionsRoute
  '/_app/reminders': typeof AppRemindersRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/vehicles': typeof AppVehiclesRoute
  '/_app/ai/chat': typeof AppAiChatRoute
  '/_app/ai/damage': typeof AppAiDamageRoute
  '/_app/ai/forecast': typeof AppAiForecastRoute
  '/_app/ai/fraud': typeof AppAiFraudRoute
  '/_app/ai/maintenance': typeof AppAiMaintenanceRoute
  '/_app/ai/ocr-cnic': typeof AppAiOcrCnicRoute
  '/_app/ai/pricing': typeof AppAiPricingRoute
  '/_app/ai/recommend': typeof AppAiRecommendRoute
  '/_app/ai/risk': typeof AppAiRiskRoute
  '/_app/ai/signature-verify': typeof AppAiSignatureVerifyRoute
  '/_app/ai/smart-search': typeof AppAiSmartSearchRoute
  '/_app/ai/summarize': typeof AppAiSummarizeRoute
  '/_app/ai/translate': typeof AppAiTranslateRoute
  '/_app/ai/voice-booking': typeof AppAiVoiceBookingRoute
  '/_app/ai/whatsapp': typeof AppAiWhatsappRoute
  '/_app/bookings/new': typeof AppBookingsNewRoute
  '/_app/bookings/': typeof AppBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/ai'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/drivers'
    | '/form-design'
    | '/inspections'
    | '/maintenance'
    | '/payments'
    | '/promotions'
    | '/reminders'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/vehicles'
    | '/ai/chat'
    | '/ai/damage'
    | '/ai/forecast'
    | '/ai/fraud'
    | '/ai/maintenance'
    | '/ai/ocr-cnic'
    | '/ai/pricing'
    | '/ai/recommend'
    | '/ai/risk'
    | '/ai/signature-verify'
    | '/ai/smart-search'
    | '/ai/summarize'
    | '/ai/translate'
    | '/ai/voice-booking'
    | '/ai/whatsapp'
    | '/bookings/new'
    | '/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/ai'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/drivers'
    | '/form-design'
    | '/inspections'
    | '/maintenance'
    | '/payments'
    | '/promotions'
    | '/reminders'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/vehicles'
    | '/ai/chat'
    | '/ai/damage'
    | '/ai/forecast'
    | '/ai/fraud'
    | '/ai/maintenance'
    | '/ai/ocr-cnic'
    | '/ai/pricing'
    | '/ai/recommend'
    | '/ai/risk'
    | '/ai/signature-verify'
    | '/ai/smart-search'
    | '/ai/summarize'
    | '/ai/translate'
    | '/ai/voice-booking'
    | '/ai/whatsapp'
    | '/bookings/new'
    | '/bookings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/ai'
    | '/_app/calendar'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/drivers'
    | '/_app/form-design'
    | '/_app/inspections'
    | '/_app/maintenance'
    | '/_app/payments'
    | '/_app/promotions'
    | '/_app/reminders'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/vehicles'
    | '/_app/ai/chat'
    | '/_app/ai/damage'
    | '/_app/ai/forecast'
    | '/_app/ai/fraud'
    | '/_app/ai/maintenance'
    | '/_app/ai/ocr-cnic'
    | '/_app/ai/pricing'
    | '/_app/ai/recommend'
    | '/_app/ai/risk'
    | '/_app/ai/signature-verify'
    | '/_app/ai/smart-search'
    | '/_app/ai/summarize'
    | '/_app/ai/translate'
    | '/_app/ai/voice-booking'
    | '/_app/ai/whatsapp'
    | '/_app/bookings/new'
    | '/_app/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vehicles': {
      id: '/_app/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reminders': {
      id: '/_app/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promotions': {
      id: '/_app/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AppPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspections': {
      id: '/_app/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/form-design': {
      id: '/_app/form-design'
      path: '/form-design'
      fullPath: '/form-design'
      preLoaderRoute: typeof AppFormDesignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers': {
      id: '/_app/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings/': {
      id: '/_app/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AppBookingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings/new': {
      id: '/_app/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof AppBookingsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/whatsapp': {
      id: '/_app/ai/whatsapp'
      path: '/whatsapp'
      fullPath: '/ai/whatsapp'
      preLoaderRoute: typeof AppAiWhatsappRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/voice-booking': {
      id: '/_app/ai/voice-booking'
      path: '/voice-booking'
      fullPath: '/ai/voice-booking'
      preLoaderRoute: typeof AppAiVoiceBookingRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/translate': {
      id: '/_app/ai/translate'
      path: '/translate'
      fullPath: '/ai/translate'
      preLoaderRoute: typeof AppAiTranslateRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/summarize': {
      id: '/_app/ai/summarize'
      path: '/summarize'
      fullPath: '/ai/summarize'
      preLoaderRoute: typeof AppAiSummarizeRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/smart-search': {
      id: '/_app/ai/smart-search'
      path: '/smart-search'
      fullPath: '/ai/smart-search'
      preLoaderRoute: typeof AppAiSmartSearchRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/signature-verify': {
      id: '/_app/ai/signature-verify'
      path: '/signature-verify'
      fullPath: '/ai/signature-verify'
      preLoaderRoute: typeof AppAiSignatureVerifyRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/risk': {
      id: '/_app/ai/risk'
      path: '/risk'
      fullPath: '/ai/risk'
      preLoaderRoute: typeof AppAiRiskRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/recommend': {
      id: '/_app/ai/recommend'
      path: '/recommend'
      fullPath: '/ai/recommend'
      preLoaderRoute: typeof AppAiRecommendRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/pricing': {
      id: '/_app/ai/pricing'
      path: '/pricing'
      fullPath: '/ai/pricing'
      preLoaderRoute: typeof AppAiPricingRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/ocr-cnic': {
      id: '/_app/ai/ocr-cnic'
      path: '/ocr-cnic'
      fullPath: '/ai/ocr-cnic'
      preLoaderRoute: typeof AppAiOcrCnicRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/maintenance': {
      id: '/_app/ai/maintenance'
      path: '/maintenance'
      fullPath: '/ai/maintenance'
      preLoaderRoute: typeof AppAiMaintenanceRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/fraud': {
      id: '/_app/ai/fraud'
      path: '/fraud'
      fullPath: '/ai/fraud'
      preLoaderRoute: typeof AppAiFraudRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/forecast': {
      id: '/_app/ai/forecast'
      path: '/forecast'
      fullPath: '/ai/forecast'
      preLoaderRoute: typeof AppAiForecastRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/damage': {
      id: '/_app/ai/damage'
      path: '/damage'
      fullPath: '/ai/damage'
      preLoaderRoute: typeof AppAiDamageRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/chat': {
      id: '/_app/ai/chat'
      path: '/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AppAiChatRouteImport
      parentRoute: typeof AppAiRoute
    }
  }
}

interface AppAiRouteChildren {
  AppAiChatRoute: typeof AppAiChatRoute
  AppAiDamageRoute: typeof AppAiDamageRoute
  AppAiForecastRoute: typeof AppAiForecastRoute
  AppAiFraudRoute: typeof AppAiFraudRoute
  AppAiMaintenanceRoute: typeof AppAiMaintenanceRoute
  AppAiOcrCnicRoute: typeof AppAiOcrCnicRoute
  AppAiPricingRoute: typeof AppAiPricingRoute
  AppAiRecommendRoute: typeof AppAiRecommendRoute
  AppAiRiskRoute: typeof AppAiRiskRoute
  AppAiSignatureVerifyRoute: typeof AppAiSignatureVerifyRoute
  AppAiSmartSearchRoute: typeof AppAiSmartSearchRoute
  AppAiSummarizeRoute: typeof AppAiSummarizeRoute
  AppAiTranslateRoute: typeof AppAiTranslateRoute
  AppAiVoiceBookingRoute: typeof AppAiVoiceBookingRoute
  AppAiWhatsappRoute: typeof AppAiWhatsappRoute
}

const AppAiRouteChildren: AppAiRouteChildren = {
  AppAiChatRoute: AppAiChatRoute,
  AppAiDamageRoute: AppAiDamageRoute,
  AppAiForecastRoute: AppAiForecastRoute,
  AppAiFraudRoute: AppAiFraudRoute,
  AppAiMaintenanceRoute: AppAiMaintenanceRoute,
  AppAiOcrCnicRoute: AppAiOcrCnicRoute,
  AppAiPricingRoute: AppAiPricingRoute,
  AppAiRecommendRoute: AppAiRecommendRoute,
  AppAiRiskRoute: AppAiRiskRoute,
  AppAiSignatureVerifyRoute: AppAiSignatureVerifyRoute,
  AppAiSmartSearchRoute: AppAiSmartSearchRoute,
  AppAiSummarizeRoute: AppAiSummarizeRoute,
  AppAiTranslateRoute: AppAiTranslateRoute,
  AppAiVoiceBookingRoute: AppAiVoiceBookingRoute,
  AppAiWhatsappRoute: AppAiWhatsappRoute,
}

const AppAiRouteWithChildren = AppAiRoute._addFileChildren(AppAiRouteChildren)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDriversRoute: typeof AppDriversRoute
  AppFormDesignRoute: typeof AppFormDesignRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPromotionsRoute: typeof AppPromotionsRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppVehiclesRoute: typeof AppVehiclesRoute
  AppBookingsNewRoute: typeof AppBookingsNewRoute
  AppBookingsIndexRoute: typeof AppBookingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDriversRoute: AppDriversRoute,
  AppFormDesignRoute: AppFormDesignRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPromotionsRoute: AppPromotionsRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppVehiclesRoute: AppVehiclesRoute,
  AppBookingsNewRoute: AppBookingsNewRoute,
  AppBookingsIndexRoute: AppBookingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
